name = "notification-worker"
main = "worker.js"
compatibility_date = "2024-09-23"
compatibility_flags = [ "nodejs_compat" ]

# Specify the Cloudflare Workers runtime
workers_dev = true

# Observability Settings
[observability]
enabled = true