name = "notification-worker"
main = "worker.js"
compatibility_date = "2024-09-23"
compatibility_flags = [ "nodejs_compat" ]

# Specify the Cloudflare Workers runtime
workers_dev = true

# Observability Settings
[observability]
enabled = true

# Cron Trigger (runs every minute)
[triggers]
crons = ["* * * * *"]

# Environment Variables
[vars]
DATABASE_URL= "" # Set this in the Cloudflare dashboard or with wrangler secret
RESEND_API_KEY = "" # Set this in the Cloudflare dashboard or with wrangler secret
CLERK_SECRET_KEY = "" # Set this in the Cloudflare dashboard or with wrangler secret